version: "3.7"
services:
  data-collector-service:
    build:
      context: .
      dockerfile: ./data-collector-service/data-collector-service.dockerfile
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    env_file: ".env"

  central-service:
    build:
      context: central-service
      dockerfile: ./central-service.dockerfile
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    env_file: ".env"
